steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/stanford-medical-agent:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/stanford-medical-agent:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'stanford-medical-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/stanford-medical-agent:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8501'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'SUPABASE_URL=${_SUPABASE_URL},SUPABASE_SERVICE_KEY=${_SUPABASE_SERVICE_KEY},ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY},GROQ_API_KEY=${_GROQ_API_KEY},GOOGLE_GENERATIVE_AI_API_KEY=${_GOOGLE_GENERATIVE_AI_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/stanford-medical-agent:$COMMIT_SHA'

substitutions:
  _SUPABASE_URL: 'your-supabase-url'
  _SUPABASE_SERVICE_KEY: 'your-supabase-service-key'
  _ANTHROPIC_API_KEY: 'your-anthropic-api-key'
  _GROQ_API_KEY: 'your-groq-api-key'
  _GOOGLE_GENERATIVE_AI_API_KEY: 'your-google-api-key' 